/// <mls fileReference="_102035_/l2/agentNewSolution/helpers/ns4WidgetPhrases.ts" enhancement="_blank"/>

/**
 * English catalogue slice for the E1-E6 clarification widgets.
 * Merged into NS4_PHRASES so the root planner translates widget chrome once per run.
 */

export const NS4_WIDGET_PHRASES = {
  'widget.intake.adjustmentRequired': 'Describe what should change before generating another proposal.',
  'widget.intake.processingApproval': 'Validating initial definition…',
  'widget.intake.processingChanges': 'Preparing a new review…',
  'widget.intake.processingCancel': 'Cancelling execution…',
  'widget.intake.revise': 'Review the items below',
  'widget.intake.cancel': 'Cancel execution',
  'widget.intake.cancelTitle': 'Cancel this execution?',
  'widget.intake.cancelText': 'Processing will end. The history and approved artifacts will be preserved.',
  'widget.intake.keepWorking': 'Keep working',
  'widget.journeys.subtitle': 'These journeys will become the permanent source of truth for the product.',
  'widget.journeys.actor': 'Actor',
  'widget.journeys.goal': 'Goal',
  'widget.journeys.steps': 'Steps',
  'widget.journeys.rules': 'Rules',
  'widget.journeys.outcome': 'Outcome and evidence',
  'widget.journeys.filters': 'Filters',
  'widget.journeys.impact': 'Impact',
  'widget.journeys.noPolicyDecision': 'No policy decision was provided for this journey.',
  'widget.journeys.journeys': 'Journeys',
  'widget.journeys.journeysFound': 'journeys found',
  'widget.journeys.selectJourney': 'Select a journey to review.',
  'widget.journeys.allActors': 'All actors',
  'widget.journeys.actorMap': 'Journey map by actor',
  'widget.journeys.actors': 'actors',
  'widget.journeys.overview': 'Overview',
  'widget.journeys.actual': '(actual)',
  'widget.journeys.rulesHelp': 'Rules that must remain true in every execution of this journey.',
  'widget.journeys.adjustment': 'What should change?',
  'widget.journeys.placeholder': 'Describe the needed change without rewriting what is already correct.',
  'widget.journeys.requestChanges': 'Request changes',
  'widget.journeys.approve': 'Approve journeys',
  'widget.journeys.round': 'Review',
  'widget.journeys.step': 'Step',
  'widget.journeys.of': 'of',
  'widget.journeys.adjustmentRequired': 'Describe what must change before requesting another version.',
  'widget.journeys.processingApproval': 'Validating journeys…',
  'widget.journeys.processingChanges': 'Preparing a new review…',
  'widget.journeys.processingCancel': 'Cancelling execution…',
  'widget.journeys.revise': 'Review the items below',
  'widget.journeys.cancel': 'Cancel execution',
  'widget.journeys.cancelTitle': 'Cancel this execution?',
  'widget.journeys.cancelText': 'Processing will end. The history and approved artifacts will be preserved.',
  'widget.journeys.keepWorking': 'Keep working',
  'widget.journeys.assumedDecisions': 'Assumed decisions',
  'widget.journeys.changeHint': 'How to change later',
  'widget.accessMatrix.subtitle': 'Review who may perform each capability and exactly which information may be disclosed.',
  'widget.accessMatrix.step': 'Step',
  'widget.accessMatrix.of': 'of',
  'widget.accessMatrix.round': 'Review',
  'widget.accessMatrix.profiles': 'Access profiles',
  'widget.accessMatrix.internal': 'Internal',
  'widget.accessMatrix.external': 'External',
  'widget.accessMatrix.actors': 'E2 actors',
  'widget.accessMatrix.landing': 'Starting point',
  'widget.accessMatrix.matrix': 'Profile \u00d7 authority matrix',
  'widget.accessMatrix.profileAccess': 'Authorities for this profile',
  'widget.accessMatrix.authority': 'Authority',
  'widget.accessMatrix.noAccess': 'No access',
  'widget.accessMatrix.full': 'Full record',
  'widget.accessMatrix.limited': 'Limited',
  'widget.accessMatrix.details': 'Access details',
  'widget.accessMatrix.reason': 'Business reason',
  'widget.accessMatrix.scope': 'Data scope',
  'widget.accessMatrix.disclosure': 'Disclosure boundary',
  'widget.accessMatrix.allowed': 'May expose',
  'widget.accessMatrix.denied': 'Must not expose',
  'widget.accessMatrix.ruleRefs': 'Rule references',
  'widget.accessMatrix.journeySteps': 'Journey steps',
  'widget.accessMatrix.informationNeeds': 'Information needs',
  'widget.accessMatrix.close': 'Close',
  'widget.accessMatrix.adjustment': 'What should change?',
  'widget.accessMatrix.placeholder': 'Example: Add authority to view project budgets; some clients may see a summary without seeing the whole project.',
  'widget.accessMatrix.requestChanges': 'Generate another proposal',
  'widget.accessMatrix.approve': 'Approve access matrix',
  'widget.accessMatrix.adjustmentRequired': 'Describe the required change before generating another proposal.',
  'widget.accessMatrix.empty': 'No access matrix available.',
  'widget.accessMatrix.processingApproval': 'Validating access matrix…',
  'widget.accessMatrix.processingChanges': 'Preparing a new review…',
  'widget.accessMatrix.processingCancel': 'Cancelling execution…',
  'widget.accessMatrix.revise': 'Review the items below',
  'widget.accessMatrix.cancel': 'Cancel execution',
  'widget.accessMatrix.cancelTitle': 'Cancel this execution?',
  'widget.accessMatrix.cancelText': 'Processing will end. The history and approved artifacts will be preserved.',
  'widget.accessMatrix.keepWorking': 'Keep working',
  'widget.ontology.subtitle': 'Review the business data, constraints and relationships that frontend and backend will share.',
  'widget.ontology.step': 'Step',
  'widget.ontology.of': 'of',
  'widget.ontology.round': 'Review',
  'widget.ontology.mode': 'New solution',
  'widget.ontology.changes': 'Changes in this round',
  'widget.ontology.entities': 'Entities',
  'widget.ontology.fields': 'Fields',
  'widget.ontology.relationships': 'Relationships',
  'widget.ontology.lifecycle': 'Lifecycle',
  'widget.ontology.ruleRefs': 'Rule references',
  'widget.ontology.overview': 'Overview',
  'widget.ontology.descriptions': 'Descriptions',
  'widget.ontology.source': 'Traceability',
  'widget.ontology.storage': 'Persistence destination',
  'widget.ontology.required': 'Required',
  'widget.ontology.optional': 'Optional',
  'widget.ontology.constraints': 'Field rules',
  'widget.ontology.persistenceMap': 'Persistence map',
  'widget.ontology.persistenceHint': 'Confirm where every entity lives before approval. Select an entity to inspect its reason and fields.',
  'widget.ontology.targetMdm': 'MDM · base records',
  'widget.ontology.targetModuleDatabase': 'Module database · transactions',
  'widget.ontology.targetDerived': 'Derived · no own table',
  'widget.ontology.targetExternal': 'External · platform owned',
  'widget.ontology.targetEmbedded': 'Embedded · owned value',
  'widget.ontology.scope': 'Scope',
  'widget.ontology.mdmType': 'MDM type',
  'widget.ontology.idField': 'Identifier',
  'widget.ontology.reason': 'Reason',
  'widget.ontology.fieldRulesHint': 'Click a field name or description to edit it in place.',
  'widget.ontology.crossStore': 'Cross-store',
  'widget.ontology.sourceRelationships': 'As origin',
  'widget.ontology.destinationRelationships': 'As destination',
  'widget.ontology.noRelationships': 'No relationships for this table.',
  'widget.ontology.implementation': 'Field binding',
  'widget.ontology.editInPlace': 'Click to edit',
  'widget.ontology.direct': 'Direct description edits',
  'widget.ontology.directHint': 'Titles and descriptions are safe to edit here. Structural changes use the separate request panel.',
  'widget.ontology.entityTitle': 'Entity title',
  'widget.ontology.entityDescription': 'Entity description',
  'widget.ontology.fieldTitle': 'Field title',
  'widget.ontology.fieldDescription': 'Field description',
  'widget.ontology.structural': 'What should change?',
  'widget.ontology.structuralHint': 'Use the LLM for entities, fields, types, relationships, lifecycle or constraints.',
  'widget.ontology.placeholder': 'Example: add a client-facing published material-usage projection related to Project, without exposing internal costs.',
  'widget.ontology.request': 'Generate another proposal',
  'widget.ontology.approve': 'Approve ontology',
  'widget.ontology.requiredAdjustment': 'Describe the structural change first.',
  'widget.ontology.empty': 'No ontology proposal available.',
  'widget.ontology.processingApproval': 'Validating ontology…',
  'widget.ontology.processingChanges': 'Preparing a new review…',
  'widget.ontology.processingCancel': 'Cancelling execution…',
  'widget.ontology.revise': 'Review the items below',
  'widget.ontology.cancel': 'Cancel execution',
  'widget.ontology.cancelTitle': 'Cancel this execution?',
  'widget.ontology.cancelText': 'Processing will end. The history and approved artifacts will be preserved.',
  'widget.ontology.keepWorking': 'Keep working',
  'widget.ontology.assumedDecisions': 'Assumed decisions',
  'widget.ontology.changeHint': 'How to change later',
  'widget.rules.step': '👤 Step 5 of 6 — Business rules',
  'widget.rules.review': 'Review',
  'widget.rules.rules': 'rules',
  'widget.rules.search': 'Search by ID or description',
  'widget.rules.noRule': 'No rules found.',
  'widget.rules.adjustment': 'What should change?',
  'widget.rules.placeholder': 'Example: change clientAvailable to allow only one active client per project.',
  'widget.rules.request': 'Generate another proposal',
  'widget.rules.approve': 'Approve rules',
  'widget.rules.cancel': 'Cancel execution',
  'widget.rules.adjustmentRequired': 'Describe the required change before generating another proposal.',
  'widget.rules.processingApproval': 'Validating rules…',
  'widget.rules.processingChanges': 'Preparing another review…',
  'widget.rules.processingCancel': 'Cancelling execution…',
  'widget.rules.revise': 'Review the items below',
  'widget.rules.cancelTitle': 'Cancel this execution?',
  'widget.rules.cancelText': 'Processing will end. Approved artifacts will be preserved.',
  'widget.rules.keepWorking': 'Keep working',
  'widget.rules.hint': 'Each permanent rule contains only a stable ID and one business description.',
  'widget.rules.edit': 'Click to edit the description',
  'widget.composition.step': '👤 Step 6 of 6 — Additional modules and plugins',
  'widget.composition.review': 'Review',
  'widget.composition.empty': 'No additional horizontal module or plugin was recommended.',
  'widget.composition.horizontalModule': 'Horizontal module',
  'widget.composition.plugin': 'Plugin',
  'widget.composition.include': 'Include',
  'widget.composition.defer': 'Defer',
  'widget.composition.adjustment': 'Would you like to change anything?',
  'widget.composition.placeholder': 'Example: add, remove or defer a recommendation and explain why.',
  'widget.composition.request': 'Generate another proposal',
  'widget.composition.approve': 'Approve analysis',
  'widget.composition.cancel': 'Cancel execution',
  'widget.composition.adjustmentRequired': 'Describe the change before generating another proposal.',
  'widget.composition.processingApproval': 'Validating analysis…',
  'widget.composition.processingChanges': 'Preparing another review…',
  'widget.composition.processingCancel': 'Cancelling execution…',
  'widget.composition.revise': 'Review the items below',
  'widget.composition.cancelTitle': 'Cancel this execution?',
  'widget.composition.cancelText': 'Processing will end. Approved artifacts will be preserved.',
  'widget.composition.keepWorking': 'Keep working',
  'widget.composition.hint': 'This review is conservative: an empty list means the module can proceed without additional components.',
} as const;

export const NS4_WIDGET_KEYS = {
  intake: [
    'adjustmentRequired',
    'processingApproval',
    'processingChanges',
    'processingCancel',
    'revise',
    'cancel',
    'cancelTitle',
    'cancelText',
    'keepWorking',
  ] as const,
  journeys: [
    'subtitle',
    'actor',
    'goal',
    'steps',
    'rules',
    'outcome',
    'filters',
    'impact',
    'noPolicyDecision',
    'journeys',
    'journeysFound',
    'selectJourney',
    'allActors',
    'actorMap',
    'actors',
    'overview',
    'actual',
    'rulesHelp',
    'adjustment',
    'placeholder',
    'requestChanges',
    'approve',
    'round',
    'step',
    'of',
    'adjustmentRequired',
    'processingApproval',
    'processingChanges',
    'processingCancel',
    'revise',
    'cancel',
    'cancelTitle',
    'cancelText',
    'keepWorking',
    'assumedDecisions',
    'changeHint',
  ] as const,
  accessMatrix: [
    'subtitle',
    'step',
    'of',
    'round',
    'profiles',
    'internal',
    'external',
    'actors',
    'landing',
    'matrix',
    'profileAccess',
    'authority',
    'noAccess',
    'full',
    'limited',
    'details',
    'reason',
    'scope',
    'disclosure',
    'allowed',
    'denied',
    'ruleRefs',
    'journeySteps',
    'informationNeeds',
    'close',
    'adjustment',
    'placeholder',
    'requestChanges',
    'approve',
    'adjustmentRequired',
    'empty',
    'processingApproval',
    'processingChanges',
    'processingCancel',
    'revise',
    'cancel',
    'cancelTitle',
    'cancelText',
    'keepWorking',
  ] as const,
  ontology: [
    'subtitle',
    'step',
    'of',
    'round',
    'mode',
    'changes',
    'entities',
    'fields',
    'relationships',
    'lifecycle',
    'ruleRefs',
    'overview',
    'descriptions',
    'source',
    'storage',
    'required',
    'optional',
    'constraints',
    'persistenceMap',
    'persistenceHint',
    'targetMdm',
    'targetModuleDatabase',
    'targetDerived',
    'targetExternal',
    'targetEmbedded',
    'scope',
    'mdmType',
    'idField',
    'reason',
    'fieldRulesHint',
    'crossStore',
    'sourceRelationships',
    'destinationRelationships',
    'noRelationships',
    'implementation',
    'editInPlace',
    'direct',
    'directHint',
    'entityTitle',
    'entityDescription',
    'fieldTitle',
    'fieldDescription',
    'structural',
    'structuralHint',
    'placeholder',
    'request',
    'approve',
    'requiredAdjustment',
    'empty',
    'processingApproval',
    'processingChanges',
    'processingCancel',
    'revise',
    'cancel',
    'cancelTitle',
    'cancelText',
    'keepWorking',
    'assumedDecisions',
    'changeHint',
  ] as const,
  rules: [
    'step',
    'review',
    'rules',
    'search',
    'noRule',
    'adjustment',
    'placeholder',
    'request',
    'approve',
    'cancel',
    'adjustmentRequired',
    'processingApproval',
    'processingChanges',
    'processingCancel',
    'revise',
    'cancelTitle',
    'cancelText',
    'keepWorking',
    'hint',
    'edit',
  ] as const,
  composition: [
    'step',
    'review',
    'empty',
    'horizontalModule',
    'plugin',
    'include',
    'defer',
    'adjustment',
    'placeholder',
    'request',
    'approve',
    'cancel',
    'adjustmentRequired',
    'processingApproval',
    'processingChanges',
    'processingCancel',
    'revise',
    'cancelTitle',
    'cancelText',
    'keepWorking',
    'hint',
  ] as const,
} as const;
